# Generated by Django 3.2.19 on 2023-05-22 21:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_album_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
    ]
